name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Package Lambda function
        run: |
          rm -rf .git
          zip -r function.zip .

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name archive-positions \
            --zip-file fileb://function.zip